# Generated by Django 2.2.19 on 2021-06-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(help_text='Price to be used while charging the user')),
                ('display_price', models.CharField(blank=True, help_text='Price to show the user, eg: $6/month', max_length=250, null=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Order in which the tier will be rendered', null=True)),
                ('trial_duration', models.PositiveIntegerField(default=0, help_text='Number of days allowed for trial')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='users.Tier'),
        ),
    ]
