# Generated by Django 2.2.24 on 2021-11-30 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210909_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription Customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription ID'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='a3c206f25b694b2e90c616d995ee0f21', editable=False, max_length=32)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('subscription_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='subscription id')),
                ('monthly', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(default='8b10f3e7aee34381983a7baf99d116bb', editable=False, max_length=32)),
                ('invoice_stripe_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='invoice stripe id')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_orders', to='users.Orders')),
            ],
            options={
                'verbose_name': 'Invoices',
                'verbose_name_plural': 'Invoice',
                'db_table': 'invoices',
                'default_permissions': (),
            },
        ),
    ]
