# Generated by Django 2.2.19 on 2021-07-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('artist', models.CharField(blank=True, max_length=250, null=True)),
                ('backstory', models.TextField(blank=True)),
                ('normal_audio', models.FileField(upload_to=music.models.song_upload_path_handler)),
                ('spacial_audio', models.FileField(blank=True, null=True, upload_to=music.models.song_upload_path_handler)),
                ('normal_audio_with_meditation', models.FileField(blank=True, null=True, upload_to=music.models.song_upload_path_handler)),
                ('spacial_audio_with_meditation', models.FileField(blank=True, null=True, upload_to=music.models.song_upload_path_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('celebrity_name', models.CharField(blank=True, max_length=250, null=True)),
                ('songs', models.ManyToManyField(to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('songs', models.ManyToManyField(to='music.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_min', models.PositiveIntegerField()),
                ('start_sec', models.PositiveIntegerField()),
                ('end_min', models.PositiveIntegerField()),
                ('end_sec', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('songs', models.ManyToManyField(to='music.Song')),
            ],
        ),
    ]
