# Generated by Django 2.2.19 on 2021-07-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album'),
        ),
        migrations.AddField(
            model_name='mood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moods'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.Artist'),
        ),
    ]
