# Generated by Django 2.2.19 on 2021-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210820_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.TextField(blank=True, help_text="Enter ';' seperated values for different entries", null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='engineering',
            field=models.TextField(blank=True, help_text="Enter ';' seperated values for different entries", null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrumentalist',
            field=models.TextField(blank=True, help_text="Enter ';' seperated values for different entries", null=True),
        ),
    ]
