# Generated by Django 2.2.24 on 2021-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210820_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='vocals',
            field=models.TextField(blank=True, help_text="Enter ';' seperated values for different entries", null=True),
        ),
    ]
